services:

  backend:
    image: shalu1400/house-price-prediction:latest
    container_name: house-price-prediction
    ports:
      - "8000:8000"

    environment:
      MLFLOW_TRACKING: http://YOUR_MLFLOW_SERVER:5000

    restart: unless-stopped